# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IdsLog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IdsLog.proto',
  package='',
  serialized_pb=_b('\n\x0cIdsLog.proto\"#\n\x03Pid\x12\x10\n\x08venderId\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\t\"R\n\x0bPlatformIds\x12\x0b\n\x03zid\x18\x01 \x02(\t\x12\x12\n\x04pids\x18\x02 \x03(\x0b\x32\x04.Pid\x12\x11\n\ttimestamp\x18\x03 \x02(\x03\x12\x0f\n\x07\x61\x64verId\x18\x04 \x02(\x05\x42\x1c\n\x1a\x63om.zamplus.protobuf.uclog')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PID = _descriptor.Descriptor(
  name='Pid',
  full_name='Pid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='venderId', full_name='Pid.venderId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Pid.id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=51,
)


_PLATFORMIDS = _descriptor.Descriptor(
  name='PlatformIds',
  full_name='PlatformIds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zid', full_name='PlatformIds.zid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pids', full_name='PlatformIds.pids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PlatformIds.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adverId', full_name='PlatformIds.adverId', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=135,
)

_PLATFORMIDS.fields_by_name['pids'].message_type = _PID
DESCRIPTOR.message_types_by_name['Pid'] = _PID
DESCRIPTOR.message_types_by_name['PlatformIds'] = _PLATFORMIDS

Pid = _reflection.GeneratedProtocolMessageType('Pid', (_message.Message,), dict(
  DESCRIPTOR = _PID,
  __module__ = 'IdsLog_pb2'
  # @@protoc_insertion_point(class_scope:Pid)
  ))
_sym_db.RegisterMessage(Pid)

PlatformIds = _reflection.GeneratedProtocolMessageType('PlatformIds', (_message.Message,), dict(
  DESCRIPTOR = _PLATFORMIDS,
  __module__ = 'IdsLog_pb2'
  # @@protoc_insertion_point(class_scope:PlatformIds)
  ))
_sym_db.RegisterMessage(PlatformIds)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.zamplus.protobuf.uclog'))
# @@protoc_insertion_point(module_scope)
