# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracking.proto',
  package='',
  serialized_pb=_b('\n\x0etracking.proto\"\xb6\x01\n\nSmartpixel\x12\x14\n\x0crequest_time\x18\x01 \x02(\x03\x12\n\n\x02ip\x18\x02 \x02(\r\x12\x0e\n\x06status\x18\x03 \x02(\x05\x12\x0b\n\x03uri\x18\x04 \x02(\t\x12\x0b\n\x03zid\x18\x05 \x02(\t\x12\r\n\x05param\x18\x06 \x02(\t\x12\x0c\n\x04\x62ody\x18\x07 \x02(\t\x12\n\n\x02ua\x18\x08 \x02(\t\x12\x14\n\x0cprocess_time\x18\t \x02(\x03\x12\r\n\x05refer\x18\n \x02(\t\x12\x0e\n\x06\x63ookie\x18\x0b \x02(\t\"\xb9\x01\n\tCommonLog\x12\x14\n\x0crequest_time\x18\x01 \x02(\x03\x12\n\n\x02ip\x18\x02 \x02(\r\x12\x0e\n\x06status\x18\x03 \x02(\x05\x12\x0b\n\x03uri\x18\x04 \x02(\t\x12\x0b\n\x03zid\x18\x05 \x02(\t\x12\r\n\x05param\x18\x06 \x02(\t\x12\x0c\n\x04\x62ody\x18\x07 \x02(\t\x12\n\n\x02ua\x18\x08 \x02(\t\x12\x14\n\x0cprocess_time\x18\t \x02(\x03\x12\r\n\x05refer\x18\n \x02(\t\x12\x12\n\nrequest_id\x18\x0b \x01(\t\"\xa8\x01\n\x0cSdkCommonLog\x12\x14\n\x0crequest_time\x18\x01 \x02(\x03\x12\n\n\x02ip\x18\x02 \x02(\r\x12\x0e\n\x06status\x18\x03 \x02(\x05\x12\x0b\n\x03uri\x18\x04 \x02(\t\x12\x0b\n\x03uid\x18\x05 \x02(\t\x12\r\n\x05param\x18\x06 \x02(\t\x12\x0c\n\x04\x62ody\x18\x07 \x02(\t\x12\n\n\x02ua\x18\x08 \x02(\t\x12\x14\n\x0cprocess_time\x18\t \x02(\x03\x12\r\n\x05refer\x18\n \x02(\tB\x1f\n\x1d\x63om.zamplus.protobuf.tracking')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SMARTPIXEL = _descriptor.Descriptor(
  name='Smartpixel',
  full_name='Smartpixel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_time', full_name='Smartpixel.request_time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Smartpixel.ip', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Smartpixel.status', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uri', full_name='Smartpixel.uri', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zid', full_name='Smartpixel.zid', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='Smartpixel.param', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='Smartpixel.body', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ua', full_name='Smartpixel.ua', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_time', full_name='Smartpixel.process_time', index=8,
      number=9, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refer', full_name='Smartpixel.refer', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cookie', full_name='Smartpixel.cookie', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=201,
)


_COMMONLOG = _descriptor.Descriptor(
  name='CommonLog',
  full_name='CommonLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_time', full_name='CommonLog.request_time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='CommonLog.ip', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='CommonLog.status', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uri', full_name='CommonLog.uri', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zid', full_name='CommonLog.zid', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='CommonLog.param', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='CommonLog.body', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ua', full_name='CommonLog.ua', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_time', full_name='CommonLog.process_time', index=8,
      number=9, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refer', full_name='CommonLog.refer', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='CommonLog.request_id', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=389,
)


_SDKCOMMONLOG = _descriptor.Descriptor(
  name='SdkCommonLog',
  full_name='SdkCommonLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_time', full_name='SdkCommonLog.request_time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='SdkCommonLog.ip', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='SdkCommonLog.status', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uri', full_name='SdkCommonLog.uri', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='SdkCommonLog.uid', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='SdkCommonLog.param', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='SdkCommonLog.body', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ua', full_name='SdkCommonLog.ua', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_time', full_name='SdkCommonLog.process_time', index=8,
      number=9, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refer', full_name='SdkCommonLog.refer', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=560,
)

DESCRIPTOR.message_types_by_name['Smartpixel'] = _SMARTPIXEL
DESCRIPTOR.message_types_by_name['CommonLog'] = _COMMONLOG
DESCRIPTOR.message_types_by_name['SdkCommonLog'] = _SDKCOMMONLOG

Smartpixel = _reflection.GeneratedProtocolMessageType('Smartpixel', (_message.Message,), dict(
  DESCRIPTOR = _SMARTPIXEL,
  __module__ = 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:Smartpixel)
  ))
_sym_db.RegisterMessage(Smartpixel)

CommonLog = _reflection.GeneratedProtocolMessageType('CommonLog', (_message.Message,), dict(
  DESCRIPTOR = _COMMONLOG,
  __module__ = 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:CommonLog)
  ))
_sym_db.RegisterMessage(CommonLog)

SdkCommonLog = _reflection.GeneratedProtocolMessageType('SdkCommonLog', (_message.Message,), dict(
  DESCRIPTOR = _SDKCOMMONLOG,
  __module__ = 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:SdkCommonLog)
  ))
_sym_db.RegisterMessage(SdkCommonLog)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035com.zamplus.protobuf.tracking'))
# @@protoc_insertion_point(module_scope)
